/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_aheadlcx_myjni_EncryUtil */

#ifndef _Included_me_aheadlcx_myjni_EncryUtil
#define _Included_me_aheadlcx_myjni_EncryUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_aheadlcx_myjni_EncryUtil
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_aheadlcx_myjni_EncryUtil_get
  (JNIEnv *, jobject);

/*
 * Class:     me_aheadlcx_myjni_EncryUtil
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_aheadlcx_myjni_EncryUtil_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
